### ISSUE TITLE
Hello everyone. ı write all things on the post. ı couldnt understand why ı am getting these errors on chrome. any help or idea ?

### ISSUE THREAD

**Issue by IstanbulFatih61** [NonFactors/AspNetCore.Lookup#18]
// Controller
```
public class AnaSayfaController : BaseController
{ 
        private ApplicationDbContext _context { get; }

        public AnaSayfaController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Deneme()
        {
            return View(_context.Ulkeler.AsQueryable());
        }


        [HttpGet]
        public JsonResult Ulkeler(LookupFilter filter)
        {
            UlkeLookup lookup = new UlkeLookup(_context);
            lookup.Filter = filter;
            return Json(lookup.GetData());
        }
}
```

// view

```
@model IQueryable<Application.Models.Ulkeler>
@{
  ViewData["Title"] = "Trying Something";
  Layout = "~/Views/AnaSayfa/_anaSayfaLayout.cshtml";
}
<link href="~/lib/mvc-lookup/css/mvc-lookup.css" rel="stylesheet" />
<partial name="MvcLookup/_Dialog" />

<div mvc-lookup="Lookup" url="Ulkeler" title="Ulkeler" ></div>

// also tried with SelectedUlkeId 

<div mvc-lookup="SelectedUlkeId " url="Ulkeler" title="Ulkeler" ></div>

// with lookup-for its giving an arror also

<div mvc-lookup-for="SelectedUlkeId " url="Ulkeler" title="Ulkeler" ></div>

//error
CS1061 C# does not contain a definition for and no accessible extension method accepting a first
argument of type could be found (are you missing a using directive or an assembly reference?)



<script src="~/lib/mvc-lookup/js/mvc-lookup.js"></script>
<script type="text/javascript">
  document.querySelectorAll(".mvc-lookup").forEach(element => new MvcLookup(element));
</script>
```

// UlkeLookUp

```
public class UlkeLookup : ALookup<Ulkeler>
    {
        private ApplicationDbContext _db { get; }
        public UlkeLookup(ApplicationDbContext db)
        {
            _db = db;
            FilterCase = LookupFilterCase.Lower;
        }
        public override IQueryable<Ulkeler> GetModels()
        {
            return _db.Ulkeler.AsQueryable();
        }
    }

```
// model

```
 public class Ulkeler
    {
        [Key]
        [LookupColumn]
        public long SelectedUlkeId { get; set; }

        [LookupColumn]
        [StringLength(200)]
        public string UlkeAdi { get; set; }
    }

```
// errors on Chrome not Visual Studio

```
mvc-lookup.js:211 Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined
at MvcLookupDialog.renderHeader (mvc-lookup.js:211) at MvcLookupDialog.render (mvc-lookup.js:196) at mvc-lookup.js:165   renderHeader @ mvc-lookup.js:211 render @ mvc-lookup.js:196 (anonymous)  @ mvc-lookup.js:1655 

mvc-lookup.js:479 Uncaught (in promise) TypeError: data.rows is not iterable at mvc-lookup.js:479
at mvc-lookup.js:811 (anonymous) @ mvc-lookup.js:479 (anonymous) @ mvc-lookup.js:811
```

**Comment by Muchiachio** [comment]
What response do you get from `Ulkeler` action? You can check that in network tab.
![image](https://user-images.githubusercontent.com/6647444/79630817-4bb02c80-815d-11ea-9c7b-cf02b5adf0c5.png)

**Comment by IstanbulFatih61** [comment]
Yes I checked. data is coming ı think
![1](https://user-images.githubusercontent.com/63843654/79631030-caf23000-815e-11ea-8a84-f9acfcc72868.png)

**Comment by Muchiachio** [comment]
Lookup expects `camelCased` response, not sure how you got them `PascalCased` as asp net core uses camel case by default. You should be able to configure it per project or per response I suppose.

**Comment by IstanbulFatih61** [comment]
and also when ı want 99 record from` Ulkeler` action, its giving me to 99 record. its working but when it comes to show them to lookup or modal its passing these errors. interesting.
![2](https://user-images.githubusercontent.com/63843654/79631179-04776b00-8160-11ea-8430-b364c2b6133b.png)

**Comment by IstanbulFatih61** [comment]
and here is the `camelCase`  results but result is the same... nothing changed.
![3](https://user-images.githubusercontent.com/63843654/79631850-3c80ad00-8164-11ea-9da6-95469a16ca06.png)

**Comment by Muchiachio** [comment]
Doesn't look like `Columns`, `Columns[i].CssClass`, `Rows`, `Selected`, etc properties are camel cased.

**Comment by IstanbulFatih61** [comment]
I solve it thank you so much... and a great work is this. hope to see you !.
![5](https://user-images.githubusercontent.com/63843654/79633948-4dcfb680-8170-11ea-9dbf-86f2fa133bce.png)
![7](https://user-images.githubusercontent.com/63843654/79633988-83749f80-8170-11ea-9012-33918ef0039f.png)

**Comment by IstanbulFatih61** [comment]
again hello to everyone. ı have three question about this perfect pulgin. ı am working with this about 2 days ant ı like it so much. but ı have some ideas and questions for it. is there a feature that when ı want to get not ıd, the props name directly ? when ı use mvc-lookup attribute for Id and the props name always coming the ıd. is there any feature that can ı get the props name ? or if not can you add? this was the first.
![3](https://user-images.githubusercontent.com/63843654/79721619-57315e00-82eb-11ea-852d-1e6759859fb8.png)

and the second one is about searching results for ex. when we are searching something and the results can me more than 50-60-70 and this time the box are going down so much. so my question; is there any option about restrict search results with ten or five or twenty as the same `rows="10"` arrtibute ? if not can you add this feature  ?

this is unexpected result;
![2](https://user-images.githubusercontent.com/63843654/79722175-3ddce180-82ec-11ea-83bb-55e97e328255.png)


and the expected is this;
![1](https://user-images.githubusercontent.com/63843654/79722028-08d08f00-82ec-11ea-8b2e-62625c5d601d.png)
