### ISSUE TITLE
again hello to everyone. ı have two question about this perfect pulgin.

### ISSUE THREAD

**Issue by IstanbulFatih61** [NonFactors/AspNetCore.Lookup#19]
again hello to everyone. ı have three question about this perfect pulgin. ı am working with this about 2 days ant ı like it so much. but ı have some ideas and questions for it. is there a feature that when ı want to get not ıd, the props name directly ? when ı use mvc-lookup attribute for Id and the props name always coming the ıd. is there any feature that can ı get the props name ? or if not can you add? this was the first.
![3](https://user-images.githubusercontent.com/63843654/79721619-57315e00-82eb-11ea-852d-1e6759859fb8.png)

and the second one is about searching results for ex. when we are searching something and the results can me more than 50-60-70 and this time the box are going down so much. so my question; is there any option about restrict search results with ten or five or twenty as the same `rows="10"` arrtibute ? if not can you add this feature  ?

this is unexpected result;
![2](https://user-images.githubusercontent.com/63843654/79722175-3ddce180-82ec-11ea-83bb-55e97e328255.png)

and the expected is this;
![1](https://user-images.githubusercontent.com/63843654/79722028-08d08f00-82ec-11ea-8b2e-62625c5d601d.png)

_Originally posted by @IstanbulFatih61 in https://github.com/NonFactors/AspNetCore.Lookup/issues/18#issuecomment-616346724_

**Comment by Muchiachio** [comment]
Not sure what you need but lookup always uses `Id` name to get real lookup value so it can't be changed that easily. You can change id values through `GetId` function or add any other data you need like prop names by overriding `Alookup<T>.FormData` method or getting them from `data.columns` in javascript.

You can limit autocomplete rows by using client side [lookup api](https://mvc-lookup.azurewebsites.net/api). There is no dropdown like behavior of scrolling long data lists, you could however mimic that by returning all data from the controller and applying some styling on the autocomplete if you need to. But that would be worse than just using a dropdown.

**Comment by IstanbulFatih61** [comment]
thank you ! ı solved it..
