### ISSUE TITLE
View model binding with multi="true"

### ISSUE THREAD

**Issue by cesarsouza** [NonFactors/AspNetCore.Lookup#20]
Hi there,

First of all, thanks a lot for sharing your work, your libraries are really useful! 

I am opening this issue to ask a question. How can one bind the selected IDs from the lookup control to a list of IDs in a view model?

I see in https://mvc-lookup.azurewebsites.net/ that we can pass an integer array to the "value" property of the tag helper, but I am afraid this value works just one way, i.e. selected items would not be added back to the original array. Is that correct?

I have also seen in http://mvc-datalist.azurewebsites.net/ that one could call ```DatalistFor(model => model.Ids, ...)``` to bind an integer array to a model. Is this also possible to do with the Lookup tag helper? Also, which types this list should be? ```IList<int>``` ?

Thanks!
Cesar

**Comment by Muchiachio** [comment]
Any enumerable should work.
