### ISSUE TITLE
KEY properties named differently than "Id"

### ISSUE THREAD

**Issue by mephzara** [NonFactors/AspNetCore.Lookup#21]
It would be nice if a data annotation "LookupKey" or something similar could be used to mark the key.

Thanks a lot for the great controls & best regards

Andreas Kardin

**Comment by Muchiachio** [comment]
It currently uses `ALookup<T>.GetId` function to get the value, which you can change. Automatic filtering uses `[KeyAttribute]` with a fallback to `Id` property, which you can also override in `FilterByIds` and `FilterBynotIds` methods. There is a little inconsistency here which we could improve, but it's already possible to change.

**Comment by mephzara** [comment]
Thanks a lot for the hint `ALookup<T>.GetId`. I missed that. Works like a charm.

Regards
Andreas
