### ISSUE TITLE
filter "like" or "StartsWith"

### ISSUE THREAD

**Issue by valzak74** [NonFactors/AspNetCore.Lookup#22]
Hi,
I implement the filter option (using AdditionalFilters). But it only filter my data with streight filter values. Here is my controller function:
        public JsonResult НоменклатураБезЗапчастей(LookupFilter filter, string? фАртикул, string? фПроизводитель)
        {
            filter.AdditionalFilters["Артикул"] = фАртикул;
            filter.AdditionalFilters["Производитель"] = фПроизводитель;

            return Json(new НоменклатураLookup(_context, 1) { Filter = filter }.GetData());
        }

Here is my lookup override function:
        public override IQueryable<Номенклатура> FilterByAdditionalFilters(IQueryable<Номенклатура> models)
        {
            if (!string.IsNullOrEmpty((string?)Filter.AdditionalFilters["Производитель"]))
                models = models.Where(model => model.Производитель.StartsWith(Filter.AdditionalFilters["Производитель"].ToString()));
            if (!string.IsNullOrEmpty((string?)Filter.AdditionalFilters["Артикул"]))
                models = models.Where(model => model.Артикул.StartsWith(Filter.AdditionalFilters["Артикул"].ToString()));

            return base.FilterByAdditionalFilters(models);
        }
I debug FilterByAdditionalFilters function result and see that it containts several model items. But at result lookup window i see only one item whitch have Артикул = filter value

**Comment by Muchiachio** [comment]
You should probably not call `base.FilterByAdditionalFilters(models)` as it will apply `equals` filter on top of your starts with filters.

**Comment by valzak74** [comment]
return base.FilterByAdditionalFilters(models);
Is a result of my override function FilterByAdditionalFilters

**Comment by Muchiachio** [comment]
Yes, but it's callback to the default lookup implementation which is overfiltering, do you get expected data with `return models;`?

**Comment by valzak74** [comment]
yes. I debug the result of my override FilterByAdditionalFilters function and get 12 items of models witch satisfy the condition "Value.StartWith("300")". But in my lookup window i see only 1 item witch have Value == "300"

**Comment by valzak74** [comment]
Ah ok. Get it. The result of my override function must be filtered models but not base.FilterByAdditionalFilters(models)
You should change your example to fix that (as it was taken from it)
Thx...

**Comment by Muchiachio** [comment]
Well the example is showing both automatic and custom filter usage, so it needs base call.
In your case you needed to rewrote whole filtering to be starts with, so it doesn't need base call.
Will see if we can improve example to use only customer filters or add comments on base calls.
