### ISSUE TITLE
 id="z______" in mvc-lookup-values and the same in mvc-lookup-control

### ISSUE THREAD

**Issue by valzak74** [NonFactors/AspNetCore.Lookup#23]
Hi. In my View I have:
<div id="myId" name="myName" mvc-lookup-for="dataField" url="LookupGetModels" filters="filter1,filter2" title="Title_1" placeholder="myPlaceholder" data-toggle="collapse" data-target="#myFilters" aria-expanded="true" aria-controls="myFilters"></div>

Here is my controller "LookupGetModels":
        [HttpGet("LookupGetModels")]
        public JsonResult GetData(LookupFilter filter, string filter1, string filter2)
        {
            filter.AdditionalFilters["Col_1"] = filter1;
            filter.AdditionalFilters["Col_2"] = filter2;

            return Json(new myLookup(_context) { Filter = filter }.GetData());
        }

Here is myLookup GetModels():
        public override IQueryable<myObject> GetModels()
        {
            IQueryable<myObject> table = 
                            from vzNomNoZak in _context.VzNomenNoZap
                            join sc8840 in _context.Sc8840 on vzNomNoZak.Sp8842 equals sc8840.Id into _sc8840
                            from sc8840 in _sc8840.DefaultIfEmpty()
                            where vzNomNoZak.Ismark == false && vzNomNoZak.Isfolder == 2 
                                && !sc8840.Descr.EndsWith("some")
                                && !sc8840.Descr.EndsWith("else*")
                            select new myObject
                            {
                                Id = vzNomNoZak.Id,
                                Col_1= vzNomNoZak.Sp85.Trim(),
                                Col_2= vzNomNoZak.Descr.Trim(),
                            };
            return table;
        }
Id & Col_1 & Col_2 - strings

As a result I have on my web-page:
<div class="mvc-lookup-values" data-for="dataField"><input autocomplete="off" class="mvc-lookup-value" data-val="true" data-val-required="dataField required" id="z______" name="dataField" type="hidden" value="   ARLA  "></div>
The same I have in "mvc-lookup-controls"

1) What is " id="z______" and how can I change it to needed id
2) Is it any way to check asp-validation-for="dataField" as in my Model it have attribute [Required] ?

**Comment by valzak74** [comment]
For some reason my View is not paste to the original issue. Here it is:

<div id="myId" name="myName" mvc-lookup-for="dataField" url="LookupGetModels" filters="filter1,filter2" title="myTitle" placeholder="select myObject..." data-toggle="collapse" data-target="#myFilters" aria-expanded="true" aria-controls="myFilters"></div>

**Comment by valzak74** [comment]
hmm... html tags not shown

**Comment by Muchiachio** [comment]
1. It was most likely generated by mvc framework by escaping non [a-z] characters when generating input name/id.
Id is generated by the same rules a normal input tag helper does it, by converting C# expression name or using named variable.
```HTML
<div mvc-lookup-for="<C# expression>" />
<div mvc-lookup="<name>" />
```
2. Yes you can by using custom validator. [Here's](https://github.com/NonFactors/AspNetCore.Template/blob/8d7a748ee607257b0a6aa16b80b43a613d684979/src/MvcTemplate.Web/wwwroot/js/shared/widgets/validator.js#L34-L58) a similar validator, but it might need to be adapted to your validation library.

**Comment by valzak74** [comment]
thank a lot
