### ISSUE TITLE
form submit with lookup value from own class 

### ISSUE THREAD

**Issue by valzak74** [NonFactors/AspNetCore.Lookup#24]
Hi,
i have form with lookup 
"public class myLookup : ALookup<myObject>"

and myObject is class like:
    public class myObject 
    {
        [Key]
        [LookupColumn(Hidden = true)]
        public string Id { get; set; }
         [LookupColumn]
        public string Code { get; set; }
}
When I select myOblect from lookup I see "value=Key"
And when I submit the form myObject is null
So before submit I have to calc and get myObject by Key value?

**Comment by Muchiachio** [comment]
`MyObject` is only used as lookup model, you should use your actual domain model in the form for example `Person.CountryId`.
