### ISSUE TITLE
Get input text on "lookupadd" event listener

### ISSUE THREAD

**Issue by valzak74** [NonFactors/AspNetCore.Lookup#25]
Hi,
Is there any way to get search string while getting click on "+ Add" autocomplete?
I want to send this string to modal window.

I have such function:
Mylookup.addEventListener("lookupadd", e => {
    $("#newCustomer").modal("show");
});

But seems that e.detail.lookup doesn't contain needed information.

**Comment by Muchiachio** [comment]
Should be in `e.detail.lookup.search.value`.

**Comment by valzak74** [comment]
that's it. Thx.
